#!/bin/bash

# Shut down Splunk & Cassandra

# UNDONE: Don't hardcode Cassandra location

sudo $SPLUNK_HOME/bin/splunk stop
wait $!

pushd /home/blovering/Projects/apache-cassandra-0.7.6-2/bin
if [ -e cassandra.pid ]
then 
    kill `cat cassandra.pid`
else
    pids=`pgrep -f cassandra`
    if [ "$pids" != "" ]
    then
        pgrep -f cassandra | xargs kill -9
        wait
    fi
fi
popd
