#!/bin/bash

# Shut down Splunk & Cassandra

sudo $SPLUNK_HOME/bin/splunk stop
wait $!

pushd $CASSANDRA_HOME
if [ -e cassandra.pid ]
then 
    kill `cat cassandra.pid`
else
    pids=`pgrep -f cassandra`
    if [ "$pids" != "" ]
    then
        pgrep -f cassandra | xargs kill -9
        wait
    fi
fi
popd
